/*!
 * @file c_backend_sweep_main.cpp
 * Measure AOT C backend coverage across a whole game.
 *
 * The ordered source list comes from the project's own build definition (game.gp): every
 * `goalc` step reachable from a make target, in the order the make system would build it. Each
 * source is compiled into one shared compiler instance, exactly like the make system does, and C
 * is emitted for every file instead of only the last one.
 */

#include <cstdio>
#include <exception>
#include <optional>
#include <string>
#include <vector>

#include "common/log/log.h"
#include "common/util/FileUtil.h"
#include "common/util/string_util.h"

#include "goalc/aot/CBackend.h"
#include "goalc/compiler/Compiler.h"

namespace {

struct Options {
  std::string game = "jak1";
  std::string project_file;
  std::string target = "GROUP:all-code";
  std::string report_path;
  std::string c_output_dir;
  std::string project_path;
  std::vector<std::string> extra_sources;
  int limit = 0;
};

void print_usage() {
  std::fprintf(stderr,
               "Usage: goalc-cbackend-sweep [--game jak1] [--project-file goal_src/jak1/game.gp]\n"
               "                            [--target GROUP:all-code]\n"
               "                            [--c-output-dir DIR] [--report OUT.tsv]\n"
               "                            [--project-path OPENGOAL_ROOT] [--limit N]\n"
               "                            [--extra-source FILE.gc]...\n"
               "\n"
               "--limit stops after the first N sources in build order, for building a boot\n"
               "prefix instead of the whole game.\n"
               "--extra-source compiles a source that is not part of the game after that\n"
               "prefix, for building a test fixture on top of a real kernel.\n"
               "--c-output-dir also writes each file's header and aot_boot_manifest.{h,c},\n"
               "which lists every emitted file in build order.\n");
}

bool parse_options(int argc, char** argv, Options* options) {
  for (int i = 1; i < argc; i++) {
    const std::string argument = argv[i];
    if (argument == "--help" || argument == "-h") {
      print_usage();
      return false;
    }
    if (++i == argc) {
      std::fprintf(stderr, "Missing value for %s\n", argument.c_str());
      return false;
    }
    if (argument == "--game") {
      options->game = argv[i];
    } else if (argument == "--project-file") {
      options->project_file = argv[i];
    } else if (argument == "--target") {
      options->target = argv[i];
    } else if (argument == "--report") {
      options->report_path = argv[i];
    } else if (argument == "--c-output-dir") {
      options->c_output_dir = argv[i];
    } else if (argument == "--project-path") {
      options->project_path = argv[i];
    } else if (argument == "--extra-source") {
      options->extra_sources.push_back(argv[i]);
    } else if (argument == "--limit") {
      options->limit = std::atoi(argv[i]);
    } else {
      std::fprintf(stderr, "Unknown option %s\n", argument.c_str());
      return false;
    }
  }
  return true;
}

std::vector<std::string> ordered_goal_sources(const MakeSystem& make, const std::string& target) {
  std::vector<std::string> sources;
  for (const auto& output : make.get_dependencies(target)) {
    const auto* step = make.find_step(output);
    if (step && step->tool == "goalc" && !step->input.empty()) {
      sources.push_back(step->input.at(0));
    }
  }
  return sources;
}

std::string escape_field(const std::string& text) {
  std::string out;
  for (char c : text) {
    out += (c == '\t' || c == '\n' || c == '\r') ? ' ' : c;
  }
  return out;
}

struct ManifestEntry {
  std::string source;
  std::string tag;
};

/*!
 * The emitted files in build order, in a form the runtime can walk.
 *
 * Each generated file exports its statics, its function table and its link function. The two
 * counts are `extern const int`, which C will not accept as an array initializer, so the manifest
 * holds their addresses instead of their values.
 */
void write_manifest(const std::string& dir, const std::vector<ManifestEntry>& entries) {
  std::string header;
  header += "/* Generated by goalc-cbackend-sweep. Do not edit. */\n#pragma once\n";
  header += "#include \"goalc/aot/goal_c_runtime.h\"\n\n";
  header += "typedef struct {\n";
  header += "  const char* source;  /* the GOAL source this came from */\n";
  header += "  const char* tag;     /* what the emitted code looks itself up by */\n";
  header += "  const goal_static_desc* statics;\n";
  header += "  const int* static_count;\n";
  header += "  const void* const* functions;\n";
  header += "  const int* function_count;\n";
  header += "  void (*link)(void);\n";
  header += "} goal_aot_boot_entry;\n\n";
  header += "extern const goal_aot_boot_entry goal_aot_boot_files[];\n";
  header += "extern const int goal_aot_boot_file_count;\n";
  file_util::write_text_file(dir + "/aot_boot_manifest.h", header);

  std::string source;
  source += "/* Generated by goalc-cbackend-sweep. Do not edit. */\n";
  source += "#include \"aot_boot_manifest.h\"\n\n";
  for (const auto& entry : entries) {
    source += fmt::format("#include \"{}_generated.h\"\n", entry.tag);
  }
  source += fmt::format("\nconst goal_aot_boot_entry goal_aot_boot_files[{}] = {{\n",
                        std::max<size_t>(entries.size(), 1));
  for (const auto& entry : entries) {
    source += fmt::format(
        "    {{\"{}\", \"{}\", goal_{}_statics, &goal_{}_static_count, goal_{}_functions,\n"
        "     &goal_{}_function_count, goal_{}_link}},\n",
        entry.source, entry.tag, entry.tag, entry.tag, entry.tag, entry.tag, entry.tag);
  }
  if (entries.empty()) {
    source += "    {0, 0, 0, 0, 0, 0, 0},\n";
  }
  source += "};\n";
  source += fmt::format("const int goal_aot_boot_file_count = {};\n", entries.size());
  file_util::write_text_file(dir + "/aot_boot_manifest.c", source);
}

}  // namespace

int main(int argc, char** argv) {
  Options options;
  if (!parse_options(argc, argv, &options)) {
    return 2;
  }
  if (!valid_game_version(options.game)) {
    std::fprintf(stderr, "Unknown game version %s\n", options.game.c_str());
    return 2;
  }
  const GameVersion game_version = game_name_to_version(options.game);
  if (options.project_file.empty()) {
    options.project_file = fmt::format("goal_src/{}/game.gp", options.game);
  }

  lg::set_stdout_level(lg::level::warn);
  lg::set_flush_level(lg::level::warn);
  lg::initialize();

  std::optional<fs::path> project_path;
  if (!options.project_path.empty()) {
    project_path = fs::path(options.project_path);
  }
  if (!file_util::setup_project_path(project_path, true)) {
    std::fprintf(stderr, "Could not locate the OpenGOAL project root.\n");
    return 1;
  }

  Compiler compiler(game_version, emitter::InstructionSet::X86);
  std::vector<std::string> sources;
  try {
    compiler.make_system().load_project_file(file_util::get_file_path({options.project_file}));
    sources = ordered_goal_sources(compiler.make_system(), options.target);
  } catch (const std::exception& error) {
    std::fprintf(stderr, "goalc-cbackend-sweep: could not read the build definition: %s\n",
                 error.what());
    return 1;
  }
  std::fprintf(stderr, "%zu GOAL sources reachable from %s\n", sources.size(),
               options.target.c_str());

  if (!options.c_output_dir.empty()) {
    fs::create_directories(options.c_output_dir);
  }

  if (options.limit > 0 && options.limit < (int)sources.size()) {
    sources.resize((size_t)options.limit);
    std::fprintf(stderr, "limited to the first %d\n", options.limit);
  }
  for (const auto& extra : options.extra_sources) {
    sources.push_back(extra);
  }

  std::string report = "#kind\tfile\tfunction\tdetail\n";
  std::vector<ManifestEntry> manifest;
  int total_functions = 0;
  int total_emitted = 0;
  int total_native = 0;
  int failed_files = 0;

  for (size_t i = 0; i < sources.size(); i++) {
    const auto& source = sources.at(i);
    const auto tag = fs::path(source).stem().string();
    std::fprintf(stderr, "[%4zu/%4zu] %s\n", i + 1, sources.size(), source.c_str());
    try {
      auto code = compiler.get_goos().reader.read_from_file({source});
      auto* file = compiler.compile_object_file(tag, std::move(code), true);
      auto result = aot::emit_c_file(*file, tag, game_version, compiler.type_system());
      total_functions += result.total_count();
      total_emitted += result.emitted_count();
      report += fmt::format("FILE\t{}\t{}\t{}\n", source, result.emitted_count(),
                            result.total_count());
      total_native += result.native_count();
      for (const auto& f : result.functions) {
        if (f.ok) {
          continue;
        }
        if (f.native_symbol.empty()) {
          report += fmt::format("FAIL\t{}\t{}\t{}\n", source, escape_field(f.goal_name),
                                escape_field(f.error));
        } else {
          // C cannot express it, but the runtime has a hand-written implementation, so the file's
          // function table points at real code instead of a hole.
          report += fmt::format("NATIVE\t{}\t{}\t{}\n", source, escape_field(f.goal_name),
                                escape_field(f.native_symbol));
        }
      }
      if (!options.c_output_dir.empty()) {
        file_util::write_text_file(fmt::format("{}/{}.c", options.c_output_dir, result.tag),
                                   result.source);
        file_util::write_text_file(
            fmt::format("{}/{}_generated.h", options.c_output_dir, result.tag), result.header);
        manifest.push_back({source, result.tag});
      }
    } catch (const std::exception& error) {
      failed_files++;
      report += fmt::format("FILEERROR\t{}\t-\t{}\n", source, escape_field(error.what()));
      std::fprintf(stderr, "  front-end failure: %s\n", error.what());
    }
  }

  if (!options.c_output_dir.empty()) {
    write_manifest(options.c_output_dir, manifest);
  }

  report += fmt::format("TOTAL\t{}\t{}\t{}\n", sources.size(), total_emitted, total_functions);
  report += fmt::format("TOTALNATIVE\t{}\t-\t-\n", total_native);
  report += fmt::format("FILEERRORS\t{}\t-\t-\n", failed_files);
  std::fprintf(stderr,
               "%d/%d functions emitted (%.2f%%), %d supplied natively, %d files failed to "
               "compile\n",
               total_emitted, total_functions,
               total_functions ? 100.0 * total_emitted / total_functions : 0.0, total_native,
               failed_files);

  if (!options.report_path.empty()) {
    file_util::write_text_file(options.report_path, report);
  } else {
    std::fputs(report.c_str(), stdout);
  }
  return 0;
}
